### ISSUE TITLE
check completness

### ISSUE THREAD

**Issue by SilasK** [wwood/ena-fast-download#1]
Hey @wwood  Is there a way to check the completeness of the downloaded files?

**Comment by wwood** [comment]
Hi, well, sort of.

I assume you mean the actual download part, not the initial link gathering step.

The script uses `subprocess.check_call` so if it fails then the whole program will crash, so you'll know that way. I'm not sure what the behaviour of `ascp` is when something goes wrong, but I know the NCBI `prefetch` command deletes the file if it doesn't download successfully. Aside from all that, you might try `gzip -t` or and/or check that the number of reads you have downloaded is what is reported on the ENA website.

Hope that helps. It would presumably be possible to add a function to check the number of reads is correct as part of the script (i.e. that last suggestion above), but I've not looked into it.

ben
