### ISSUE TITLE
Failed to Authenticate

### ISSUE THREAD

**Issue by Rkubinski** [wwood/ena-fast-download#3]
Having the following error when running the software on a particular ENA dataset:

 File "../../software/ena-fast-download/ena-fast-download.py", line 63, in <module>
    subprocess.check_call(cmd,shell=True)
  File "/home/ec2-user/miniconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ascp -QT -l 300m -P33001 -i $HOME/.aspera/connect/etc/asperaweb_id_dsa.openssh era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/SRR524/000/SRR5245600/SRR5245600.fastq.gz .' returned non-zero exit status 1.

Any ideas ?

**Comment by wwood** [comment]
I suspect this is an issue outside the scope of this repo - what happens when you run that `ascp` command in a terminal? Hopefully that will lead somewhere helpful.

**Comment by JoeEmendo** [comment]
I found that many files listed on ebi no longer exist there, but are available via NCBI/SRA. If you're bulk downloading stuff you can create some conditional statement where if it's not found on ebi to try ncbi. In your case, it's found here; [https://sra-download.ncbi.nlm.nih.gov/traces/sra45/SRR/005122/SRR5245600](https://sra-download.ncbi.nlm.nih.gov/traces/sra45/SRR/005122/SRR5245600)

**Comment by Rkubinski** [comment]
Hi,
Thanks a lot, I will check out SRA. I will try to run the ascp command solo tomorrow as well.

Ryszard Kubinski
514-243-3966
M.Sc Candidate
Room 1312 McIntyre Medical Building

________________________________

**Comment by Rkubinski** [comment]
Forgot to answer this! SRA worked.

**Comment by wwood** [comment]
Hi @zhaoni153 the repo here takes as input a list of run identifiers, is that what you have been requesting?

**Comment by zhaoni153** [comment]
@wwood I gave the program as input the accession number at EBI, which is PRJEB15062 for this case. 
Further, for me, when I "./ena-fast-download.py -r PRJEB15062", I got error like " error: unrecognized arguments: -r" that the program fails immediately. Without the "-r", it ran a little while and then stoped with the previously mentioned error message. 

Thanks a lot, and forgive my total ignorance of python.

**Comment by wwood** [comment]
Hi, yes that is a project identifier, not a run identifier. One project often has multiple run identifiers. I suggest you read more about the relationship between the two (and it has nothing to do with Python, don't worry).

I guess you were using `-r` because it said so in the README? That was a mistake sorry - I've fixed it now, thanks for making me realise the error.

**Comment by zhaoni153** [comment]
@wwood Thanks a lot for your clarification. However, I tried to use run identifiers, which failed in the same way. I tried both 
./ena-fast-download.py SRR2085841 
and 
./ena-fast-download.py ERR1562083 

in which the second is what I would like to download, and the first is just another Run identifier that I want to try to see whether there is anything special about the other data. Very appreciate you taking time answering this.

**Comment by wwood** [comment]
Hmm, I'm not sure sorry. Appears to me as if something is currently wrong on the EBI side. Maybe try sending them a support request.

**Comment by wwood** [comment]
To be clear, this is what I see

```
~/git/ena-fast-download$ ./ena-fast-download.py ERR1739691
04/07/2020 04:13:43 PM INFO: Using aspera ssh key file: $HOME/.aspera/connect/etc/asperaweb_id_dsa.openssh
04/07/2020 04:13:43 PM INFO: Querying ENA for FTP paths for ERR1739691..
04/07/2020 04:13:45 PM INFO: Downloading 2 FTP read set(s): ftp.sra.ebi.ac.uk/vol1/fastq/ERR173/001/ERR1739691/ERR1739691_1.fastq.gz, ftp.sra.ebi.ac.uk/vol1/fastq/ERR173/001/ERR1739691/ERR1739691_2.fastq.gz
04/07/2020 04:13:45 PM INFO: Running command: ascp -QT -l 300m -P33001  -i $HOME/.aspera/connect/etc/asperaweb_id_dsa.openssh era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/ERR173/001/ERR1739691/ERR1739691_1.fastq.gz .

Session Stop  (Error: Server aborted session: No such file or directory)
Traceback (most recent call last):
  File "./ena-fast-download.py", line 106, in <module>
    subprocess.check_call(cmd,shell=True)
  File "/home/ben/miniconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ascp -QT -l 300m -P33001  -i $HOME/.aspera/connect/etc/asperaweb_id_dsa.openssh era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/ERR173/001/ERR1739691/ERR1739691_1.fastq.gz .' returned non-zero exit status 1.
```

**Comment by zhaoni153** [comment]
@wwood Exactly. I will send email to EBI to ask. I got exactly the same error as you did here. Will let you know how it goes.

By the way, because the program takes as input a run ID, which means that each time it only download one sample. If I would like to download all the samples from a study, I need to write a script to get all of them. Is this understanding correct?

Thanks a lot,

**Comment by zhaoni153** [comment]
@wwood it is weird because I am able to download the fastq file through FTP. Are you able to download anything from EBI using aspera now?

**Comment by Rkubinski** [comment]
They are migrating quite a bit of their data currently, I had trouble downloading 3 weeks ago. I would definitely reach out to them!
![image](https://user-images.githubusercontent.com/13441044/78684016-fef76680-78bd-11ea-94e1-937684f2cde9.png)

**Comment by wwood** [comment]
>I need to write a script to get all of them. Is this understanding correct?

I would just

```
cat run_ids |parallel -j ena-fast-download.py
```

Or, feel free to submit a pull request.

**Comment by zhaoni153** [comment]
@wwood Thanks for this suggestion. We may have to wait for a while for EBI due to the reason that @Rkubinski mentioned.
