### ISSUE TITLE
No FTP download URLs found

### ISSUE THREAD

**Issue by JonathonMifsud** [wwood/ena-fast-download#6]
Hi,

Thank you for this wonderful tool, it has been really helpful. I have been using this tool for a while but over the past couple days, no accessions seem to be working. I have tried this with several accessions that have previously worked with no luck. 

```
python3 ./scripts/ena-fast-download.py SRR5012117
08/09/2020 08:43:12 AM INFO: Using aspera ssh key file: $HOME/.aspera/connect/etc/asperaweb_id_dsa.openssh
08/09/2020 08:43:12 AM INFO: Querying ENA for FTP paths for SRR5012117..
08/09/2020 08:43:13 AM WARNING: No FTP download URLs found for run SRR5012117, cannot continue
```
I suspect this is not a bug is not with the tool but on the ENA side but thought I should open an issue just in case.

**Comment by JonathonMifsud** [comment]
Thanks for the fast fix!

**Comment by wwood** [comment]
No worries - thanks for the bug report, appreciate it.
