### ISSUE TITLE
No FTP download URLs found for run error

### ISSUE THREAD

**Issue by jolespin** [wwood/ena-fast-download#8]
Do you know what could be causing this issue? I haven't updated my script since the last time I ran this and it worked perfectly fine.  Could be an issue with my aspera key? 

(genome_adaptation_env) -bash-4.1$ ena-fast-download.py  ERR598955
09/01/2020 03:52:41 PM INFO: Using aspera ssh key file: $HOME/.aspera/connect/etc/asperaweb_id_dsa.openssh
09/01/2020 03:52:41 PM INFO: Querying ENA for FTP paths for ERR598955..
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/genome_adaptation_env/bin/ena-fast-download.py:67: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn("No FTP download URLs found for run {}, cannot continue".format(run_id))
09/01/2020 03:52:42 PM WARNING: No FTP download URLs found for run ERR598955, cannot continue

**Comment by wwood** [comment]
Yeh - gotta update. Happy to reopen if this is still an issue after.

**Comment by jolespin** [comment]
Worked like a charm.  Did ncbi change something?

**Comment by wwood** [comment]
ENA, not SRA, but yes, there was an API change.

Ben WoodcroftMicrobial informatics team leader
(+617) 3443 7334 (tel:(+617)%203443%207334)
Centre for Microbiome Research, Level 3, Translational Research Institute, Queensland University of Technology (https://maps.google.com/?q=Centre%20for%20Microbiome%20Research%2C%20Level%203%2C%20Translational%20Research%20Institute%2C%20Queensland%20University%20of%20Technology)

**Comment by haoyang-insitro** [comment]
I ran into this issue today. Could you help?

**Comment by wwood** [comment]
Fixed?

**Comment by haoyang-insitro** [comment]
Yes thank you!
